name: NodeJS with vite build + Publish to Comfy registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'jtydhr88' }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Publish Custom Node
      uses: Comfy-Org/publish-node-action@v1
      with:
        personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
